from __future__ import annotations

"""
费率标准化字典层。

来源：旧 `rate/datas.py` 的业务字典与表头定义。
当前做法：保留核心业务口径，统一命名，补齐中文字段 -> DB 字段映射。
"""

from typing import Final


FINAL_RATE_HEADERS_3: Final[list[str]] = [
    "公司编号",
    "公司",
    "产品编号",
    "产品",
    "投保年龄",
    "缴费期间",
    "保险期间",
    "性别",
    "固定保额/份数",
    "最小份数",
    "最大份数",
    "年金领取年龄",
    "年金领取文本",
    "特定年金领取年龄",
    "特定年金领取文本",
    "保证领取",
    "吸烟状态",
    "优选等级",
    "优选文本",
    "社保",
    "交费方式",
    "保费状态",
    "第二被保险人性别",
    "第二被保险人年龄",
    "费率",
]


CHINESE_TO_INTERNAL_FIELD: Final[dict[str, str]] = {
    "公司编号": "company_id",
    "公司": "company_name",
    "产品编号": "product_id",
    "产品": "product_name",
    "投保年龄": "age",
    "缴费期间": "payment_years",
    "交费期间": "payment_years",
    "保险期间": "insurance_period",
    "性别": "gender",
    "固定保额/份数": "amount",
    "最小份数": "min_copies",
    "最大份数": "max_copies",
    "年金领取年龄": "annuity_age",
    "年金领取文本": "annuity_age_text",
    "特定年金领取年龄": "special_annuity_age",
    "特定年金领取文本": "special_annuity_age_text",
    "保证领取": "guaranteed_payment",
    "吸烟状态": "smoke",
    "优选等级": "preferred_grade",
    "优选文本": "preferred_text",
    "社保": "social_security",
    "交费方式": "pay_type",
    "保费状态": "premium_status",
    "第二被保险人性别": "secondary_gender",
    "第二被保险人年龄": "secondary_age",
    "费率": "rate",
}


INTERNAL_TO_DB_FIELD: Final[dict[str, str]] = {
    "company_id": "company_id",
    "company_name": "company_name",
    "product_id": "product_id",
    "product_name": "product_name",
    "age": "age",
    "payment_years": "payment_years",
    "insurance_period": "insurance_period",
    "gender": "gender",
    "amount": "amount",
    "min_copies": "min_copies",
    "max_copies": "max_copies",
    "annuity_age": "annuity_age",
    "annuity_age_text": "annuity_age_text",
    "special_annuity_age": "special_annuity_age",
    "special_annuity_age_text": "special_annuity_age_text",
    "guaranteed_payment": "guaranteed_payment",
    "smoke": "smoke",
    "preferred_grade": "preferred_grade",
    "preferred_text": "preferred_text",
    "social_security": "social_security",
    "pay_type": "pay_type",
    "premium_status": "premium_status",
    "secondary_gender": "secondary_gender",
    "secondary_age": "secondary_age",
    "rate": "rate",
}


CORE_CMB_PRODUCT_RATE_FIELDS: Final[list[str]] = [
    "product_id",
    "amount",
    "rate",
    "age",
    "gender",
    "payment_years",
    "insurance_period",
    "pay_type",
    "company_name",
    "product_name",
]


COMPANY_NAME_ALIASES: Final[dict[str, str]] = {
    "中荷": "中荷人寿",
    "和泰": "和泰人寿",
    "瑞泰": "瑞泰人寿",
}


COMPANY_ID_BY_NAME: Final[dict[str, str]] = {
    "国寿股份": "101",
    "太保寿险": "102",
    "平安人寿": "103",
    "新华人寿": "104",
    "泰康人寿": "105",
    "太平人寿": "106",
    "建信人寿": "107",
    "天安人寿": "108",
    "光大永明": "109",
    "民生人寿": "110",
    "富德生命": "111",
    "国寿存续": "112",
    "平安养老": "113",
    "中融人寿": "114",
    "合众人寿": "115",
    "太平养老": "116",
    "人保健康": "117",
    "华夏人寿": "118",
    "君康人寿": "119",
    "信泰人寿": "120",
    "农银人寿": "121",
    "长城人寿": "122",
    "昆仑健康": "123",
    "和谐健康": "124",
    "人保寿险": "125",
    "国华人寿": "126",
    "国寿养老": "127",
    "长江养老": "128",
    "英大人寿": "129",
    "泰康养老": "130",
    "幸福人寿": "131",
    "阳光人寿": "132",
    "百年人寿": "133",
    "中邮人寿": "134",
    "安邦人寿": "135",
    "利安人寿": "136",
    "前海人寿": "137",
    "华汇人寿": "138",
    "东吴人寿": "139",
    "珠江人寿": "140",
    "弘康人寿": "141",
    "吉祥人寿": "142",
    "安邦养老": "143",
    "渤海人寿": "144",
    "国联人寿": "145",
    "太保安联": "146",
    "上海人寿": "147",
    "中华人寿": "148",
    "新华养老": "149",
    "中宏人寿": "150",
    "中德安联": "151",
    "工银安盛": "152",
    "中信保诚": "153",
    "交银康联": "154",
    "中意人寿": "155",
    "友邦保险": "156",
    "北大方正": "157",
    "中荷人寿": "158",
    "中英人寿": "159",
    "同方全球": "160",
    "招商信诺": "161",
    "长生人寿": "162",
    "恒安标准": "163",
    "瑞泰人寿": "164",
    "中法人寿": "165",
    "华泰人寿": "166",
    "陆家嘴国泰": "167",
    "中美联泰": "168",
    "平安健康": "169",
    "中银三星": "170",
    "恒大人寿": "171",
    "新光海航": "172",
    "汇丰人寿": "173",
    "君龙人寿": "174",
    "复星保德信": "175",
    "中韩人寿": "176",
    "德华安顾": "177",
    "华贵人寿": "178",
    "横琴人寿": "179",
    "复星健康": "180",
    "信美人寿": "181",
    "爱心人寿": "182",
    "和泰人寿": "183",
    "众安财产": "184",
    "安联财险": "185",
    "招商仁和": "186",
    "北京人寿": "187",
    "三峡人寿": "188",
    "国宝人寿": "189",
    "海保人寿": "190",
    "易安财产": "191",
    "国富人寿": "192",
    "瑞华健康": "193",
    "中华财险": "194",
    "太平财险": "195",
    "人保财险": "196",
    "太保产险": "197",
    "阳光财险": "198",
    "安心保险": "199",
}


INSURANCE_PERIOD_NORMALIZATION_MAP: Final[dict[str, str]] = {
    "10": "10年",
    "10年": "10年",
    "20": "20年",
    "20年": "20年",
    "30": "30年",
    "30年": "30年",
    "40": "40年",
    "50": "50年",
    "60": "60年",
    "70": "70年",
    "80": "80年",
    "90": "90年",
    "终身": "终身",
    "保终身": "终身",
    "保至终身": "终身",
    "至60": "至60周岁",
    "至60岁": "至60周岁",
    "至60周岁": "至60周岁",
    "保至60岁": "至60周岁",
    "保至60周岁": "至60周岁",
    "至65": "至65周岁",
    "至70": "至70周岁",
    "至70岁": "至70周岁",
    "至70周岁": "至70周岁",
    "保至70岁": "至70周岁",
    "保至70周岁": "至70周岁",
    "至80": "至80周岁",
    "至80岁": "至80周岁",
    "至80周岁": "至80周岁",
    "保至80周岁": "至80周岁",
    "保至88周岁": "至88周岁",
}


PAYMENT_YEARS_NORMALIZATION_MAP: Final[dict[str, str]] = {
    "一次交清": "趸交",
    "一次性交清": "趸交",
    "保险费一次性交纳": "趸交",
    "趸缴": "趸交",
    "趸交": "趸交",
    "三年交": "3年交",
    "3年": "3年交",
    "3年交": "3年交",
    "五年交": "5年交",
    "5年": "5年交",
    "5交": "5年交",
    "5年交": "5年交",
    "十年交": "10年交",
    "10年": "10年交",
    "10年交": "10年交",
    "十五年交": "15年交",
    "15年": "15年交",
    "15年交": "15年交",
    "二十年交": "20年交",
    "20年": "20年交",
    "20年交": "20年交",
    "二十五年交": "25年交",
    "25年交": "25年交",
    "三十年交": "30年交",
    "30年": "30年交",
    "30年交": "30年交",
    "交至30岁": "交至30周岁",
    "交至55周岁": "交至55周岁",
    "交至60周岁": "交至60周岁",
}


GENDER_NORMALIZATION_MAP: Final[dict[str, int]] = {
    "不限": 0,
    "不区分": 0,
    "女性": 10,
    "女": 10,
    "男性": 11,
    "男": 11,
}


PAY_TYPE_NORMALIZATION_MAP: Final[dict[str, int]] = {
    "趸交": 0,
    "月交": 1,
    "季度交": 3,
    "季交": 3,
    "半年交": 6,
    "年交": 12,
    "不定期交": -1,
}


SOCIAL_SECURITY_NORMALIZATION_MAP: Final[dict[str, int]] = {
    "不限": 0,
    "不区分": 0,
    "无": 10,
    "无社保": 10,
    "无基本医疗保险": 10,
    "有": 11,
    "有社保": 11,
    "有基本医疗保险": 11,
}


SMOKE_NORMALIZATION_MAP: Final[dict[str, int]] = {
    "不限": 0,
    "不区分": 0,
    "否": 10,
    "不吸烟": 10,
    "是": 11,
    "吸烟": 11,
}


PREMIUM_STATUS_NORMALIZATION_MAP: Final[dict[str, int]] = {
    "不区分": 0,
    "首期": 10,
    "首保": 10,
    "续期": 11,
    "续保": 11,
}


PREFERRED_GRADE_NORMALIZATION_MAP: Final[dict[str, str]] = {
    "超优体": "1",
    "特惠体": "2",
    "优选体": "3",
    "标准体": "4",
    "不区分": "不区分",
}


DATABASE_DEFAULTS: Final[dict[str, object]] = {
    "company_id": "",
    "company_name": "",
    "product_id": "",
    "product_name": "",
    "age": 0,
    "payment_years": "",
    "insurance_period": "",
    "gender": 0,
    "amount": 1000,
    "min_copies": 1,
    "max_copies": 999999999,
    "annuity_age": 0,
    "annuity_age_text": "",
    "special_annuity_age": 0,
    "special_annuity_age_text": "",
    "guaranteed_payment": "",
    "smoke": 0,
    "preferred_grade": "",
    "preferred_text": "",
    "social_security": 0,
    "pay_type": 12,
    "premium_status": 0,
    "secondary_gender": 0,
    "secondary_age": 0,
    "rate": 0.0,
}

